// copyright discretelogics 2012. released under the gpl v3. see license.txt for details.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#Append(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#Create(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#Create(System.String,System.String,DiscreteLogics.TeaTime.Description.NameValueCollection)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#Create(System.String,DiscreteLogics.TeaTime.Diagnostics.TraceWriter,System.String,DiscreteLogics.TeaTime.Description.NameValueCollection)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#OpenRead(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#OpenRead(System.String,DiscreteLogics.TeaTime.Diagnostics.TraceWriter)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#OpenWrite(System.String,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#OpenWrite(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#Create(System.String,System.String,DiscreteLogics.TeaTime.Description.NameValueCollection)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFile`1.#Create(System.String,DiscreteLogics.TeaTime.Diagnostics.TraceWriter,System.String,DiscreteLogics.TeaTime.Description.NameValueCollection)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFileDescription.#NameValues")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1405:ComVisibleTypeBaseTypesShouldBeComVisible", Scope = "type", Target = "DiscreteLogics.TeaTime.Description.NameValueCollection")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "name", Scope = "member", Target = "DiscreteLogics.TeaTime.Description.NameValue.#Initialize(System.String,DiscreteLogics.TeaTime.Description.ValueKind,System.Object)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "sectionPayload", Scope = "member", Target = "DiscreteLogics.TeaTime.Header.Section.#Set(DiscreteLogics.TeaTime.Header.ISectionPayload)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "traceWriter", Scope = "member", Target = "DiscreteLogics.TeaTime.TeaFileCore.#Initialize(System.String,System.IO.FileShare,DiscreteLogics.TeaTime.Diagnostics.TraceWriter,System.IO.FileMode,System.IO.FileAccess)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "value", Scope = "member", Target = "DiscreteLogics.TeaTime.Description.NameValue.#Initialize(System.String,DiscreteLogics.TeaTime.Description.ValueKind,System.Object)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "value", Scope = "member", Target = "DiscreteLogics.TeaTime.Description.NameValue.#Name")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "value", Scope = "member", Target = "DiscreteLogics.TeaTime.Description.NameValue.#Value")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "value", Scope = "member", Target = "DiscreteLogics.TeaTime.Description.NameValue.#ValueKind")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "valueKind", Scope = "member", Target = "DiscreteLogics.TeaTime.Description.NameValue.#Initialize(System.String,DiscreteLogics.TeaTime.Description.ValueKind,System.Object)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "DiscreteLogics.TeaTime.Description.LayoutAnalyzer`1.#AnalyzeLayout()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.String,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Create(System.String,System.String,TeaTime.NameValueCollection)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Create(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1027:MarkEnumsWithFlags", Scope = "type", Target = "TeaTime.TeaType")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "t", Scope = "member")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "TeaTime.NameValue.#Kind")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.DateTime.ToString(System.String)", Scope = "member", Target = "TeaTime.Time.#ToString(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.IO.Stream)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.IO.Stream,System.IO.Stream)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.IO.Stream,System.IO.Stream,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.String,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Create(System.IO.Stream)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Create(System.IO.Stream,System.String,TeaTime.NameValueCollection)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.IO.Stream)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.IO.Stream,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.String,System.IO.FileShare,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.String,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.IO.Stream)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.IO.Stream,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.String,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.Convert.ChangeType(System.Object,System.Type)", Scope = "member", Target = "TeaTime.TeaFile.#GetValue(TeaTime.Item,TeaTime.Field)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Event", Scope = "type", Target = "TeaTime.Event`1")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "TeaTime.LayoutAnalyzer`1.#GetStructWithOneFieldSet(System.Collections.Generic.List`1<System.Reflection.FieldInfo>,System.Object)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.String,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "TeaTime.Header.HeaderManager.#ReadHeader(System.IO.Stream)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "preallocated", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.IO.Stream,System.Boolean,System.IO.Stream,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "FileStream", Scope = "member", Target = "TeaTime.TeaFileCore.#Name")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "TeaTime", Scope = "namespace", Target = "TeaTime")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.TeaFile.#OpenRead(System.String)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.TeaFile`1.#Create(System.String,System.String,TeaTime.NameValueCollection)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.String,System.IO.FileShare,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.String,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.String,TeaTime.ItemDescriptionDetails)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1027:MarkEnumsWithFlags", Scope = "type", Target = "TeaTime.FieldType")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "itemAreaEndMarker", Scope = "member", Target = "TeaTime.TeaFileCore.#Assign(System.Int64,System.Int64)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object,System.Object,System.Object)", Scope = "member", Target = "TeaTime.ItemDescription.#ToString(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope = "member", Target = "TeaTime.NameValue.#Kind")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "TeaTime.NameValueCollection.#From(System.Object[])")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.RawMemoryMapping.#OpenRead(System.String)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "TeaTime.TeaFile.#GetValue(TeaTime.Item,TeaTime.Field)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "TeaTime.Time.#ToString(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "TeaTime.Time.#ToString()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRawTeaFileMapping(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Create(System.String,System.String,TeaTime.NameValueCollection,System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Create(System.IO.Stream,System.String,TeaTime.NameValueCollection,System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenManagedMemoryMapping(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.RawMemoryMapping`1.#OpenRead(System.String)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.RawMemoryMapping`1.#OpenRead(System.String)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "TeaTime.UnsafeNativeMethods.UnmapViewOfFile(System.IntPtr)", Scope = "member", Target = "TeaTime.RawMemoryMapping`1.#Dispose()")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "TeaTime.UnsafeNativeMethods.CloseHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)", Scope = "member", Target = "TeaTime.RawMemoryMapping`1.#Dispose()")]

// remove default args sometime

[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.String,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.IO.Stream,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.String,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.IO.Stream,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "TeaTime.TeaFile`1.#Create(System.String,System.String,TeaTime.NameValueCollection,System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "TeaTime.TeaFile`1.#Create(System.IO.Stream,System.String,TeaTime.NameValueCollection,System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.String,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.String,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.IO.Stream,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.String,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.IO.Stream,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenWrite(System.String,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "itemAreaEnd", Scope = "member", Target = "TeaTime.TeaFileCore.#Assign(System.Int64,System.Int64)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "itemAreaStart", Scope = "member", Target = "TeaTime.TeaFileCore.#Assign(System.Int64,System.Int64)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "TeaTime.TeaFile.#GetFieldValue(TeaTime.Item,TeaTime.Field)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.TeaFile`1.#Append(System.String,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRead(System.String,TeaTime.ItemDescriptionElements)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TeaTime.Event`1.#Time")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TeaTime.Event`1.#Value")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope = "type", Target = "TeaTime.Event`1")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2217:DoNotMarkEnumsWithFlags", Scope = "type", Target = "TeaTime.ItemDescriptionElements")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "TeaTime.Item.#Values")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenMemoryMapping(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "TeaTime.TeaFile`1.#OpenRawMemoryMapping(System.String)")]
